version: '3.9'
services:
###NODERED##########
  node-red:
    container_name: nodered
    image: nodered/node-red:latest
    restart: always
    ports:
      - ${NODERED_PORT1}:1880
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CREDENTIAL_SECRET=${CREDENTIAL_SECRET}
    volumes:
      - ./nodered-data:/data
    networks:
      - compose-bridge
    depends_on:
      - rabbitmq

##RABBITMQ#######
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbitmq
    container_name: rabbitmq
    command: "/bin/bash -c \"rabbitmq-plugins enable rabbitmq_mqtt; rabbitmq-server\""
    restart: always
    ports:
      - ${RABBITMQ_PORT1}:5672
      - ${RABBITMQ_PORT2}:15672
      - ${RABBITMQ_PORT3}:1883
    networks:
      - compose-bridge  
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq-data/:/var/lib/rabbitmq

networks:
  compose-bridge:
    driver: bridge